### Simple Webhook
POST http://localhost:4000/webhook/simple 
Content-Type: application/json

{
    "message": "User Registered",
    "email": "abdul@gmail.com"
}

### Complex Webhook
POST http://localhost:4000/webhook/complex 
Content-Type: application/json

{
    "message": "User Registered",
    "email": "abdul@gmail.com"
}

### Random Webhook
POST http://localhost:4000/webhook/random 
Content-Type: application/json

{
    "message": "User Registered",
    "email": "abdul@gmail.com"
}